import type { PowerMeta, SnapshotUPS, PowerSource } from './types'

export const POWER_META: Record<PowerSource, PowerMeta> = {
  mains: {
    label: '市电供电',
    dot: 'bg-teal-500',
    text: 'text-teal-600 dark:text-teal-400',
    pill: 'border-teal-500/40 bg-teal-500/10 text-teal-700 dark:text-teal-300',
    pulse: false,
  },
  battery: {
    label: '电池供电',
    dot: 'bg-amber-500',
    text: 'text-amber-600 dark:text-amber-400',
    pill: 'border-amber-500/40 bg-amber-500/10 text-amber-700 dark:text-amber-300',
    pulse: true,
  },
  low_battery: {
    label: '电量过低',
    dot: 'bg-rose-500',
    text: 'text-rose-600 dark:text-rose-400',
    pill: 'border-rose-500/40 bg-rose-500/10 text-rose-700 dark:text-rose-300',
    pulse: true,
  },
  unknown: {
    label: '状态未知',
    dot: 'bg-muted-foreground/60',
    text: 'text-muted-foreground',
    pill: 'border-border bg-muted text-muted-foreground',
    pulse: false,
  },
}

export const RANGE_OPTIONS = [
  { value: '1h', label: '1 小时' },
  { value: '6h', label: '6 小时' },
  { value: '12h', label: '12 小时' },
  { value: '24h', label: '24 小时' },
  { value: '3d', label: '3 天' },
  { value: '7d', label: '7 天' },
]

// 隐藏式样式演示数据:主页标题左侧的状态点连点 5 次进入演示模式渲染。
// 仅用于本地预览不同电量 / 电源 / 充电状态下的电池图标效果。
export const DEMO_BATTERY_VARIANTS: SnapshotUPS[] = [
  {
    name: 'demo-75',
    mfr: 'Demo',
    model: '高电量(75)',
    power_source: 'mains',
    battery_percent: 75,
    runtime_minutes: 42,
    battery_voltage: 13.5,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 226,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OL',
    sampled_at: new Date().toISOString(),
  },
  {
    name: 'demo-35',
    mfr: 'Demo',
    model: '中电量(35)',
    power_source: 'mains',
    battery_percent: 35,
    runtime_minutes: 14,
    battery_voltage: 12.8,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 226,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OL',
    sampled_at: new Date().toISOString(),
  },
  {
    name: 'demo-12',
    mfr: 'Demo',
    model: '低电量(12)',
    power_source: 'mains',
    battery_percent: 12,
    runtime_minutes: 4,
    battery_voltage: 11.4,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 226,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OL',
    sampled_at: new Date().toISOString(),
  },
  {
    name: 'demo-chrg-60',
    mfr: 'Demo',
    model: '充电中(60)',
    power_source: 'mains',
    battery_percent: 60,
    runtime_minutes: 28,
    battery_voltage: 13.2,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 226,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OL CHRG',
    sampled_at: new Date().toISOString(),
  },
  {
    name: 'demo-chrg-35',
    mfr: 'Demo',
    model: '充电中(35)',
    power_source: 'mains',
    battery_percent: 35,
    runtime_minutes: 14,
    battery_voltage: 12.6,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 226,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OL CHRG',
    sampled_at: new Date().toISOString(),
  },
  {
    name: 'demo-chrg-12',
    mfr: 'Demo',
    model: '充电中(12)',
    power_source: 'mains',
    battery_percent: 12,
    runtime_minutes: 4,
    battery_voltage: 11.6,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 226,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OL CHRG',
    sampled_at: new Date().toISOString(),
  },
  {
    name: 'demo-bat-75',
    mfr: 'Demo',
    model: '电池供电(75)',
    power_source: 'battery',
    battery_percent: 75,
    runtime_minutes: 38,
    battery_voltage: 12.6,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 0,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OB DISCHRG',
    sampled_at: new Date().toISOString(),
  },
  {
    name: 'demo-bat-35',
    mfr: 'Demo',
    model: '电池供电(35)',
    power_source: 'battery',
    battery_percent: 35,
    runtime_minutes: 12,
    battery_voltage: 12.1,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 0,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OB DISCHRG',
    sampled_at: new Date().toISOString(),
  },
  {
    name: 'demo-bat-12',
    mfr: 'Demo',
    model: '电量过低(12)',
    power_source: 'low_battery',
    battery_percent: 12,
    runtime_minutes: 3,
    battery_voltage: 11.4,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 0,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OB LB DISCHRG',
    sampled_at: new Date().toISOString(),
  },
  {
    // demo-offline:DemoSection 里会把 sampled_at 改写为 now - 15min,触发离线样式
    name: 'demo-offline',
    mfr: 'Demo',
    model: '离线(10 分钟未上报)',
    power_source: 'unknown',
    battery_percent: 60,
    runtime_minutes: 22,
    battery_voltage: 13.4,
    battery_nominal_voltage: 12,
    battery_type: 'pbac',
    input_voltage: 225,
    output_voltage: 226,
    load_percent: 18,
    real_power: 100,
    raw_status: 'OL',
    sampled_at: new Date().toISOString(),
  },
]

export type MetricKey = 'voltage' | 'load' | 'power'
export const METRIC_OPTIONS: { value: MetricKey; label: string }[] = [
  { value: 'voltage', label: '电压' },
  { value: 'load', label: '负载' },
  { value: 'power', label: '实时功率' },
]

export const BATTERY_TYPE_LABEL: Record<string, string> = {
  pb: '铅酸',
  pbac: '铅酸',
  pbacid: '铅酸',
  lead: '铅酸',
  'lead-acid': '铅酸',
  sla: '铅酸 (SLA)',
  'sealed lead acid': '铅酸 (SLA)',
  vrla: '铅酸 (VRLA)',
  agm: '铅酸 (AGM)',
  gel: '铅酸 (Gel)',
  flooded: '铅酸 (开口)',
  'li-ion': '锂离子',
  liion: '锂离子',
  lifepo4: '磷酸铁锂',
  nicd: '镍镉',
  nimh: '镍氢',
}
